<a href="https://colab.research.google.com/github/J000lka/data-science-bootcamp/blob/main/01_wprowadzenie/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* @author: krakowiakpawel9@gmail.com  
* @site: e-smartdata.org

### NumPy
>Strona biblioteki: [https://numpy.org/](https://numpy.org/)  
>Dokumentacja: [https://numpy.org/doc/](https://numpy.org/doc/)  
>
>Podstawowa biblioteka do obliczeń numerycznych w języku Python.
>
>Aby zainstalować bibliotekę NumPy, użyj polecenia poniżej:
```
pip install numpy
```

### Spis treści:
1. [Podstawy](#a1)
2. [Typy danych](#a2)
3. [Tworzenie tablic](#a3)
4. [Podstawowe operacje na tablicach](#a4)
5. [Generowanie liczb pseudolosowych](#a5)
6. [Podstawowe funkcje](#a6)
7. [Indeksowanie, Wycinanie](#a7)
8. [Iteracja po tablicach](#a8)
9. [Zmiana rozmiaru tablic](#a9)
10. [Maski logiczne](#a10)


### <a name='a1'></a> Podstawy

np - numerical python
sprawdzamy wersję

In [3]:
import numpy as np
np.__version__

'1.21.6'

jakie mamy klasy, metody, atrybuty do wyboru

In [ ]:
dir(np)

In [ ]:
print(dir(np))

array - jedna z podstawowych funkcji do tworzenia tablic

In [ ]:
help(np.array)

1D Array

tworzenie prostej tablicy
podstawowym obiektem numpy jest wielowymiarowa tablica, kazdy element musi byc tego samego typu
w numpy wymiary są nazywane osiami (axes) a klasa to ndarray



tablica jednowymiarowa, argumenty jako lista

In [6]:
x = np.array([1, 3])
x

array([1, 3])

In [7]:
print(x)

[1 3]


In [8]:
type(x)

numpy.ndarray

atrubuty: 
liczba wymiarów
kształt - tu jest tupla, bo są dwa elementy
rozmiar - liczba elemwntów
dtype - typ danych, tu integer


In [9]:
x.ndim

1

In [10]:
x.shape

(2,)

In [11]:
x.size

2

In [12]:
x.dtype

dtype('int64')

In [13]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [14]:
x.dtype

dtype('float64')

2D Array

tablice dwuwymiarowe
 podajemy zagnieżdżone listy

In [15]:
x = np.array([[1, 2], [-3, 1]])
x

array([[ 1,  2],
       [-3,  1]])

In [17]:
x.ndim

2

In [16]:
x.shape

(2, 2)

jeśli budujemy sieć neuronową to ważżne jest poprawne posługiwanie sie wymiarami tablic, ten element powdouje poprawne działanie funkcji, któ©ą jest sieć neuronowa

In [18]:
x = np.array([[1, 2, 4], [4, 2, 1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [19]:
x.shape

(2, 3)

3D Array

tablice trójwymiarowe, np. przechowywanie obrazu

żeby ładniej wyglądało i było bardziej czytelnie

In [20]:
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],
     
     [[4, 1, 3],
      [4, 2, 1]],
     
     [[3, 2, 1],
      [4, 3, 2]]]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[3, 2, 1],
        [4, 3, 2]]])

In [21]:
x.ndim

3

trzy tablice, dwa wiersze i trzy kolumny

In [22]:
x.shape

(3, 2, 3)

### <a name='a2'></a> Typy danych

In [23]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [24]:
A = np.array([1.0, 2.3, 3.3])
A.dtype

dtype('float64')

ręcznie dodatkowy parametr dtype w konstrukcji tabeli, zeby python nie brał na podstawie tego co widzi tylko to co może się zdażyć

In [27]:
A = np.array([1, 2, 3], dtype='float')
A.dtype
print(A)

[1. 2. 3.]


In [26]:
A = np.array([1, 2, 3], dtype='complex')
A.dtype

dtype('complex128')

jeśli zzrobimy floaty a typ nadamy integer, to python obetnie to co po przecinku

In [28]:
A = np.array([1.0, 2.7, 3.3], dtype='int')
A.dtype

dtype('int64')

In [29]:
A

array([1, 2, 3])

wartości logiczne

In [30]:
A = np.array([True, False])
A.dtype

dtype('bool')

wbudowane typy danych 
np tablica, która ma opisać zdjęcie

In [31]:
A = np.array([24, 120, 230], dtype=np.int8)
A.dtype

dtype('int8')

uint8 - od 0 do 255

In [32]:
A = np.array([24, 120, 230], dtype=np.uint8)
A.dtype

dtype('uint8')

### <a name='a3'></a> Tworzenie tablic

wbudowane funkcje, które ułatwiają budowanie zaawansowanych tablic


 zeros - tablica dowolnego rozmiaru z zer

In [33]:
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

domyślnie typ float, można zmienić na int

In [34]:
np.zeros(shape=(4, 10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

taka funkcja np. do otworzenia masem do zdjęć w computer vision, np. 600 na 800 piksel, która jest czarnym tłem to np.zeros

a teraz same jedynki

In [35]:
np.ones(shape=(5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
np.ones(shape=(5, 5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

uzupełnienie dowolną wartością

In [37]:
np.full(shape=(3, 3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

generowanie danych w tablicy, tworzy się zakres, jeśli nie podamy początku i końca to od zero do n-1

In [38]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [43]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [44]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [45]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

działa podobnie do arange, parametry start, stop i num = liczba ile elementów z tego przedziału, które są równomiernie rozłożone

In [46]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [47]:
np.linspace(start=0, stop=1, num=10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

zmeinianie kształtu danych

In [48]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [49]:
A.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

automatyczne wykrywanie drugiego parametru: liczby kolumn

In [50]:
A.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

analogicznie automatyczna liczba wierszy

In [51]:
A.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

### <a name='a4'></a> Podstawowe operacje na tablicach

In [59]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


operacje są wykonywane po elementach

In [53]:
A + B

array([6, 0, 7, 4])

In [54]:
A - B

array([0, 2, 1, 0])

In [55]:
A * B

array([ 9, -1, 12,  4])

w tablicy, przez którą dzielimy nie może być zera, wyrzuca bład

In [60]:
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

dodawanie do tabeli stałej, mnozenie przez stałą, itp

In [62]:
A + 3

array([6, 4, 7, 5])

In [63]:
2 * A

array([6, 2, 8, 4])

do tego są też metody, zwłaszcza do pierwszej części

In [61]:
np.add(A, B)

array([6, 0, 7, 4])

In [64]:
np.subtract(A, B)

array([0, 2, 1, 0])

In [65]:
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [66]:
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

i wracamy do stałych

In [ ]:
A + 3*B

array([12, -2, 13,  8])

mnożenie macierzowe

na początek macierze kwadrtowe 2x2

In [4]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


jak działa mnozenie proste - mnożenie po elemencie

In [5]:
X * Y

array([[6, 0],
       [2, 0]])

a teraz mnozenie macierzowe

In [6]:
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

inny sposób zapisu, mnożenie macierzy nie jest przemienne

In [7]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [8]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

trzeci sposób zapisu

In [9]:
X @ Y

array([[  3,   6],
       [-12,   0]])

### <a name='a5'></a>  Generowanie liczb pseudolosowych

ziarno losowania, zeby za każdym razem mieć ten sm wynik

In [10]:
np.random.seed(0)

losowe z rozkładu normalnego

In [11]:
np.random.randn()

1.764052345967664

parametr - ilość losowych elementów, tablica z jednym wierszem

In [12]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

teraz 40 elementów w 10 wierszach i 4 kolumnach, np do histogramów rozkładu normalnego; wtedy pierwszy parametr można utożsamiać z liczbą próbek, a drugi z liczbą zmiennych

In [13]:
np.random.randn(10, 4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

rozkład jednostajny na przedziale [0, 1)

In [14]:
np.random.rand()

0.1965823616800535

In [15]:
np.random.rand(10)

array([0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841,
       0.97645947, 0.4686512 , 0.97676109, 0.60484552, 0.73926358])

In [16]:
np.random.rand(10, 2)

array([[0.03918779, 0.28280696],
       [0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318],
       [0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145],
       [0.26538949, 0.52324805],
       [0.09394051, 0.5759465 ],
       [0.9292962 , 0.31856895],
       [0.66741038, 0.13179786],
       [0.7163272 , 0.28940609]])

określamy w niej parametr, losuje liczbę całkowitą z przedziału 0 - parmetr

In [21]:
np.random.randint(10)

8

można podać parametry startowy i końcowy

In [20]:
np.random.randint(low=10, high=101)

70

i dookreślić ilość

In [22]:
np.random.randint(low=10, high=101, size=10)

array([87, 40, 34, 12, 13, 23, 50, 82, 29, 82])

losowy element z podanego zbioru iterowalnego

In [23]:
np.random.choice([4, 2, 1, 3, 5])

1

In [24]:
np.random.choice(['python', 'java', 'sql'])

'sql'

generujemy tablicę, można ją przetasować i to zmienia postać danych, już tablica wyglda na zawsze inaczej

In [25]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.random.shuffle(data)

In [27]:
data

array([7, 2, 1, 6, 0, 5, 9, 3, 4, 8])

### <a name='a6'></a> Podstawowe funkcje

czego nie trzeba już importować z innych bibliotek

eksponenta dla parametru 1 to stał Eulera

In [28]:
np.exp(1)

2.718281828459045

In [29]:
np.exp(4)

54.598150033144236

pierwiastek kwadratowy

In [30]:
np.sqrt(9)

3.0

przechodzi po obiekcie iterowalnym i sprawdza czy true czy falce, jeśliktórakolwiek to false to zwróci false, w p.p. zwraca true

In [32]:
np.all([2, 3, 1, 0])

False

zwrac prawdę, jeśli przynajmniej jedna prawda

In [33]:
np.any([0, 1, 0])

True

In [34]:
bool(1.3)

True

tworzymy mały obiekt na którym będziemy walczyć

przykład: mamy 5 klas i model zwraca p-stwo, że próbka należy do danej klasy

In [37]:
A = np.random.rand(5)
A

array([0.88173536, 0.69253159, 0.72525428, 0.50132438, 0.95608363])

indeks, gdzie tablica osiąga wartość największą,pmietamy, że pierwszy indeks = 0

In [38]:
np.argmax(A)

4

wycinamy tę najwyższą wartość

In [39]:
A[np.argmax(A)]

0.9560836347232239

analogicznie dla minimum

In [40]:
np.argmin(A)

3

sortowanie elementów podając indeks

In [41]:
np.argsort(A)

array([3, 1, 2, 0, 4])

czysto statystyczne

In [42]:
np.max(A)

0.9560836347232239

In [43]:
np.min(A)

0.5013243819267023

In [44]:
np.mean(A)

0.751385849680437

In [45]:
np.median(A)

0.7252542798196405

In [46]:
np.std(A)

0.15847371958621503

###  <a name='a7'></a> Indeksowanie, Wycinanie

dobieranie się do danych za pomocą indeksowania

In [47]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

jakie atrybuty możmy podać przy wycinaniu: idx - indeks (też start:stop i od do końca i do)

In [ ]:
# A[idx], A[start:stop], A[:stop], A[start:]

In [48]:
A[2]

2

pmiętać o domkniętości i otwartości nawiasów: domknięty jest OD

In [49]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [50]:
A[:2]

array([0, 1])

wycinanie konkretnych indeksów

In [51]:
A[[0, 2]]

array([0, 2])

ujemnymi liczy od końca

In [53]:
A[-1]

19

In [54]:
A[10:15]

array([10, 11, 12, 13, 14])

przekształcamy tablicę

In [55]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

wycinanie konkretnego wiersza

In [56]:
A[1]

array([5, 6, 7, 8, 9])

wycinanie kolumny

In [57]:
A[:, 2]

array([ 2,  7, 12, 17])

przedostatnia kolumna

In [58]:
A[:, -2]

array([ 3,  8, 13, 18])

chcemy konkretny element, jego położenie, np element 6

In [59]:
A[1, 1]

6

teraz 8

In [60]:
A[1, 3]

8

chcemy wyciąć kawałek ze środka,podjemy przedziały

In [61]:
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

wzmiana elementu 7 na 14

In [62]:
A[1, 2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### <a name='a8'></a> Iteracja po tablicach

In [ ]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
for row in A:
    print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [ ]:
for row in A:
    print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [ ]:
for item in A.flat:
    print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


### <a name='a9'></a> Zmiana rozmiaru tablic

In [ ]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
A.shape

(4, 5)

In [ ]:
A.reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

### <a name='a10'></a> Maski logiczne

In [ ]:
A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [ ]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
np.bitwise_and(A > -5, A < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [ ]:
np.bitwise_or(A < -5, A > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])